
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/shopping_cart?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qhw12522

  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always

  config:
    activate:
      on-profile: db

  thymeleaf:
    cache: false
