name: Deploy on deploy branch
on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v3
        with:
          ref: deploy

      - name: Execute deploy script
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
