name: Deploy to EC2

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: [self-hosted, linux, ARM64, deploy]
    defaults:
      run:
        working-directory: ../..
    steps:
      - name: deploy
        run: |
          echo $PWD
          chmod +x ./deploy.sh
          sudo ./deploy.sh



