name: Deploy to EC2

on:
  push:
    branches:
      - deploy
jobs:

  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: "."
    steps:
      - name: change permission
        run: |
          sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/jwp-shopping-order

      - name: deploy
        run: |
          echo $PWD
#          chmod +x ./deploy.sh
#          sudo ./deploy.sh



