name: Deploy to EC2

on:
  push:
    branches:
      - deploy

jobs:
  common_job:
    strategy:
      matrix:
        runner: [${{ secrets.TORI_RUNNER }}, ${{ secrets.POI_RUNNER }}, ${{ secrets.JENA_RUNNER }}]
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        working-directory: ../..
    steps:
      - name: deploy
        run: |
          echo $PWD
          chmod +x ./deploy.sh
          sudo ./deploy.sh



